/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/carousel.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Form: typeof import('./src/components/form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shopgrid: typeof import('./src/components/shopgrid.vue')['default']
    Title: typeof import('./src/components/title.vue')['default']
    Toolbar: typeof import('./src/components/toolbar.vue')['default']
  }
}
